name: mini
channels:
  - defaults
  - conda-forge
dependencies:
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - entrypoints=0.3
  - flake8=3.7.9
  - intel-openmp=2020.0
  - mccabe=0.6.1
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - mypy=0.750
  - mypy_extensions=0.4.3
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1e
  - pip=20.0.2
  - psutil=5.7.0
  - pycodestyle=2.5.0
  - pyflakes=2.1.1
  - python=3.8.2
  - scipy=1.4.1
  - setuptools=46.1.3
  - six=1.14.0
  - sqlite=3.31.1
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.1
  - wheel=0.34.2
